# Generated by Django 3.2.7 on 2021-09-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_date'),
        ('cars', '0004_auto_20200703_0748'),
    ]

    operations = [
    ]
